/**
 * Deployed Soroban Contract IDs.
 * Replace these placeholders with your actual deployed contract IDs (e.g., from `stellar contract deploy`).
 */
export const CONTRACTS = {
  HELLO_WORLD: process.env.NEXT_PUBLIC_HELLO_WORLD_CONTRACT_ID || "C_REPLACE_WITH_YOUR_CONTRACT_ID",
};

/**
 * You can also export helper functions here to import the autogenerated
 * bindings (generated via `stellar contract bindings typescript`).
 */
